### ISSUE TITLE
Is "PARAMETER_SENSOR" still needed ?

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#105]
moderator: @OceanGlidersCommunity/format-maintainers

**Is your feature request related to a problem? Please describe.**
This is an potential simplification of the format. 
Currently, we have the variable "PARAMETER_SENSOR" in the prototype used to link parameters and sensor metadata together. Current value is : "PARAMETER_SENSOR" = "CTD_PRES", "CTD_TEMP", "CTD_CNDC", "FLUOROMETER_CHLA",      "OPTODE_DOXY" ;
Since we are using groups to link sensors and parameters I wonder if this variable is still needed ? My feeling is no, but I may be wrong.

Also, I think the group name could be group attribute "type" controlled by [L05](http://vocab.nerc.ac.uk/search_nvs/L05/).

**Describe the solution you'd like**
I think we can remove PARAMETER_SENSOR variable.
I would suggest to use L05 to controlle the attribute "type" of the groups. 

Below is an exemple : 

group: CTD{
  // group attributes:
  		:long_name = "Sea-Bird SBE 41CP CTD" ;
  		:type = "CTD" ; 
  		:type_vocabulary = "https://vocab.nerc.ac.uk/collection/L05/current/130/" ;
  		:maker = "Sea-Bird Scientific" ;
  		:maker_vocabulary = "https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/" ;
  		:model = "SBE 41CP CTD " ;
  		:model_vocabulary = "https://vocab.nerc.ac.uk/collection/L22/current/TOOL0669/" ;
  		:serial_number = "75" ;
  		:calibration_date = "2019-10-22T00:00:00Z" ;
  } // group CTD

group: dissolved gas sensor {
  // group attributes:
  		:long_name = "Sea-Bird SBE 63 dissolved oxygen sensor" ;
  		:type = "dissolved gas sensor"
  		:type_vocabulary = "https://vocab.nerc.ac.uk/collection/L05/current/351/" ;
  		:maker = "Seabird" ;
  		:maker_vocabulary = "https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/" ;
  		:model = "Sea-Bird SBE 63 DO" ;
  		:model_vocabulary = "https://vocab.nerc.ac.uk/collection/L22/current/TOOL0739/" ;
  		:serial_number = "631776" ;
  		:calibration_date = "2019-11-22T00:00:00Z" ;
  } // group dissolved gas sensor

group: fluorometers {
  // group attributes:
  		:long_name = "Seapoint chlorophyll fluorometer" ;
  		:type = "fluorometers" ;
  		:type_vocabulary = "https://vocab.nerc.ac.uk/collection/L05/current/113/" ;
  		:maker = "SEAPOINT" ;
  		:maker_vocabulary = "https://vocab.nerc.ac.uk/collection/L35/current/MAN0177/" ;
  		:model = "Seapoint SCF" ;
  		:model_identifier = "http://vocab.nerc.ac.uk/collection/L22/current/TOOL0119/" ;
  		:serial_number = "S-5012" ;
  		:calibration_date = "2019-11-22T00:00:00Z" ;
  } // group fluorometers

**Comment by castelao** [comment]
Agree, we don't need `PARAMETER_SENSOR` anymore. I'll clean it right the way on #103 .

About the group naming, I think it should be a free text for the user to decide. I think it is important to have the vocabulary and the human-readable label, but those will be already in the group attribute, so no need to force the group name again. Also, for technical reasons, it might be a good idea to avoid spaces and other special characters in the group naming. What do you think?

**Comment by glidermann** [comment]
Good to hear, was never comfortable with PARAMETER_SENSOR. It seemed like a workaround hindered by limitations we no longer have. 
--
Sent from myMail for Android Friday, 09 September 2022, 01:18AM +03:00 from Guilherme Castelão  ***@***.*** :

**Comment by vturpin** [comment]
PARAMETER_SENSOR has been removed in the prototype and the format
