### ISSUE TITLE
Syntax errors in invalid CDL example

### ISSUE THREAD

**Issue by kerfoot** [OceanGlidersCommunity/OG-format-user-manual#111]
Proponent(s): @kerfoot 

Moderator: @OceanGlidersCommunity/format-maintainers

**Describe the error**

It looks like the [CDL example](https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/sp041_20191205T1757.cdl) was modified by hand, resulting in syntactic errors that prevent using ncgen to create an example NetCDF files.  The errors are primarily omission of **;** to terminate lines.

**Example**

[CDL example](https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/sp041_20191205T1757.cdl)

**Potential solution**

I've fixed the errors and successfully used ncgen to create a valid NetCDF file.  The command was

    > ncgen -4 -o sp041_20191205T1757.nc sp041_20191205T1757.cdl

**Platforms affected**

None

**Additional context**

The fixed CDL file is attached:

[sp041_20191205T1757.cdl.txt](https://github.com/OceanGlidersCommunity/OG-format-user-manual/files/9617257/sp041_20191205T1757.cdl.txt)

I had to append .txt to the file as I am unable to attach .cdl files.  The .txt extension should be removed prior to merging.

**Comment by castelao** [comment]
@kerfoot , thanks for noticing that. It is possible. In some cases, I did edit the CDL manually for the discussion, and once approved I would change my template to generate netCDFs. So it is possible that I missed some changes to my template. I'll look at that in the following days.

**Comment by castelao** [comment]
@kerfoot , thanks for reporting this. Next time, please open directly a PR to save us time. Thanks!

I'm closing this one if favor to #120. Let's move any discussion there.
