### ISSUE TITLE
TRAJECTORY name section clean

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#123]
Proponent(s): Victor Turpin

Moderator: @OceanGlidersCommunity/format-maintainers

- [x] I read the [code of conduct](https://github.com/OceanGlidersCommunity/OceanGliders/blob/main/CODE_OF_CONDUCT.md)
      and agree to follow it.
- [x] This correction should not change the meaning of the related text nor
      result in some ambiguity.
- [ ] I don't need help to create a pull request to address it.
- [x] Language **which spelling are we following**?? FIXME!!!!

## Affected text

TRAJECTORY NAME section
Removing **TRAJECTORY:data_mode_vocabulary = “”;**
Change the title of this section TRAJECTORY name into "FeatureType" (or TRAJECTORY FeatureType).

## Correction

////
* [[trajectory-name]]
== FeatureType
////
== FeatureType

[cols=",,",options="header",]
|===========================================================================================================================
|*VARIABLE NAME* |*variable attributes* |*requirement status*
|TRAJECTORY a|
string TRAJECTORY

TRAJECTORY:cf_role = "trajectory_id"

TRAJECTORY:long_name = “trajectory name”;

 a|
mandatory

Value: <platform_code>_<start_date>

Where <platform_code> refers to the name of the glider, <start_date> refers to the deployment start UTC date under iso 8601,

Ex : eltanin_20210909T1605

If the glider has no <platform_code> use <platform_serial_number> instead to create the TRAJECTORY

Ex.: sp042_20210218T2325

|===========================================================================================================================

## Explanation (if needed)

data_mode is not related to TRAJECTORY anymore (this is a legacy from an old version of the format)
Trajectory name is not correct. FeatureType is what is describe by TRAJECTORY...
I think it is more correct. This has no much importance in my view but as I went through this section I think it worth notifying.

Thank you for your contribution.

## For moderator

- [ ] Keep track of the contributor's records. If this turns into a PR and
      actually result in a modification, the moderator should keep track to
      be sure that the proper credits are given.

**Comment by castelao** [comment]
@vturpin , I'm not sure if I got your point here. Just checking, `featureType` is a CF requirement to define the DSG used [9.1 from CF](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#_features_and_feature_types), so we don't have any room to play with its value.

**Comment by vturpin** [comment]
Does not matter, I went through the doc and realize that the title of this section of the format TRAJECTORY NAME may not be appropriate.
This has no impact on the format at all.
I will close this issue based on your comment. Thanks.
