### ISSUE TITLE
PLATFORM_TYPE redundancy

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#125]
Proponent(s): Victor Turpin

Moderator: @OceanGlidersCommunity/format-maintainers

**Describe the error**
The global attribute "platform" and the variable "PLATFORM_TYPE" are redundant. I suggest to remove one of them. 

**Example**
Both value are "Sub-surface gliders"

**Potential solution**
Keep it is the global attribute, remove from variables

**Platforms affected**
all platforms are affected

**Additional context**
none

**Comment by castelao** [comment]
Since we are not concerned anymore with the aggregation of multiple platforms, it might make more sense to have it as a global attribute and be coherent with other global ones such as trajectory/deployment related ones. But I have no strong opinion on this one.
