### ISSUE TITLE
Updates to the OceanGliders vocabulary document

### ISSUE THREAD

**Issue by justinbuck** [OceanGlidersCommunity/OG-format-user-manual#129]
In order to prepare for the realease of OG1.0 we need to update the vocabularied document
https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/src/OG_Vocabulary.adoc 

Key updates needed are:
- Improve the introduction for the community to make it more accessible
- Update the initial table, add in which vocabs will be in OG1.0, update link, add in a link to the governance of each voacbulary etc
- Review subsequent tables to ensure they are consistent

**Comment by vturpin** [comment]
Work has been done on another branch.
https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/vturpin-patch-3-VocabularyCollectionSection/vocabularyCollection/tableOfControlledVocab.adoc 

There will be a reviewers team meeting end of April to validate the collections.
Meetings with Emma and NVS team has been organize already to validate the process for implementing the collections on NVS.

**Comment by vturpin** [comment]
vocab guideline has been deployed and linked to OG1.0 format
