### ISSUE TITLE
TRAJECTORY dimension needed

### ISSUE THREAD

**Issue by jenseva** [OceanGlidersCommunity/OG-format-user-manual#130]
Proponent(s): @jenseva

Moderator: @OceanGlidersCommunity/format-maintainers

Hi There,

I'm testing out using the latest CDL with Spray glider data and testing a resulting netcdf file in Panoply and ERDDAP.  

It looks like the latest CDL and users manual do not specify a Trajectory dimension, but this is required for CF 1.8 compliance. 

Latest CDL:
https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/sp041_20191205T1757-instrument-scalar_v2.cdl

User Manual:
https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/OG_Format.adoc#dimension-and-definition

**Example**
I tested generating a nc file without the trajectory dimension and ran into issues in both Panoply and ERDDAP ingest rejected it. 

**Potential solution**
So, I added a trajectory dimension to a sample file, and the new sample file behaves much better in Panoply and ERDDAP. I was making my sample file to CF-1.7 spec and then realized you all are now working towards CF-1.8. The CF-1.8 spec does change the way this is represented, so my example is close to what is needed but not exact. It looks close to "Example H.13. A single trajectory recording atmospheric composition", in the following doc.

https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_multidimensional_array_representation_of_trajectories

See my sample files and python notebook script to generate them in my test repo:
https://github.com/jenseva/og-netcdf

My guess is this was probably just an oversight and is an easy fix in the docs and example.

-Jenn

**Comment by justinbuck** [comment]
Inconsistent declarations of CF version in the documentation 1.8, 1.9, and 1.10 used. 
CF 1.8 template can be added and and the name string needs to be added.  
@jenseva to do pull request with the changes proposed

**Comment by vturpin** [comment]
This issue can be closed since we run cf compliance checker for OG1.0 format
