### ISSUE TITLE
Authorship and Methodology

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#143]
moderator: @OceanGlidersCommunity/format-maintainers

**Is your feature request related to a problem? Please describe.**
Add Authorship and Methodology sections and remove endorsment and history

**Is this related to a specific platform models**
no

**Describe the solution you'd like**
Follow authorship section used here: https://oceangliderscommunity.github.io/Oxygen_SOP/sections/authors_SOP_development_process.html 

**Describe alternatives you've considered**

**Additional context**

**Comment by callumrollo** [comment]
Hi Victor. I've started adding authors in #146. What do you have in mind for the Methodology section? Something like the SOP development process in the Oxygen SOP? A rewrite of the existing History section?

**Comment by vturpin** [comment]
Thanks for the authorship, it is pretty ok, I only made two comments in the PR as I think the list you provide does not totally reflect the reality of the contribution.

For the methodology section, I had something simple providing a bit of history and highlighting the open process. Also I am not sure we can report back the development process like the Oxygen SOP. At least I don't have the will to do it to be honest. But if someone wants to dig in this why not ! I think this is the question of Gui here: #145

Methodology
A working group on harmonization of the glider format was set in septembre 2020 on demande of the OceanGliders steering team. Any volonteers from the OceanGliders data management team was offered to join. 
The three existing format (at the time) have been analysed and compared by the group. Regular technical meetings occured and the format harmonzation process was manage with a google doc. In late 2021 the group decided to move the document to github (https://github.com/OceanGlidersCommunity/OG-format-user-manual) to better manage the issues, work asynchroneously and contribute to the community open source policy.
The Github repository was open to any comment from the community and validation rules by the working group were edited.
From there the working group organized regular meeting to validate evolutions of the format, discuss issues that needed oral explanations and finally reach a concessus on the OG1.0 format."

**Comment by callumrollo** [comment]
Thanks Victor. Can you link to the changes you want made to authorship? I can't see them on the PR. I'm happy to submit another PR replacing the history with the methodology you wrote as a starting point.

**Comment by vturpin** [comment]
I have commented this commit with the two authors I suggest to add and the two I suggest to remove: https://github.com/OceanGlidersCommunity/OG-format-user-manual/pull/146/commits/6ce6f27012b39b8b1f54f837234dc8cf6ce9589a
Do you see those comments?

And please submit another PR with the methodology section.

**Comment by callumrollo** [comment]
I still don't see any comments I'm afraid, can you post them here? I've made a PR for the methodology #147

**Comment by vturpin** [comment]
and now ? in the PR #146 ?

**Comment by callumrollo** [comment]
Resolved in #146 and #147
