### ISSUE TITLE
Transparency on authorship order 

### ISSUE THREAD

**Issue by emmerbodc** [OceanGlidersCommunity/OG-format-user-manual#148]
Moderator: @OceanGlidersCommunity/format-maintainers

Hello @callumrollo @vturpin , I saw the recent pull request for adding authors. I just wondered if the ordering could be explained please. 
Thanks,

**Comment by vturpin** [comment]
Hi Emma,

Indeed, at the moment I don't see any logic in the order. 
Initially I use alphabetical order to list the authors. Considering the authorship is the group. 
Then we move to "Github Contributors" as authors. So I assume @callum uses the order of Github contributors.
Then we adjust this list back and forth to finally remove 2 non real contributors and add Jen and John.
The current list is a mix of everything at the moment.

I would argue in favor of keeping Gui as lead, 
He did the hard work putting all this on Github and contributed a lot on the document.

Then I would use the alphabetical order.

That would give:

- [Guilherme Castelão](https://github.com/castelao) _(lead)_, Scripps Institution of Oceanography - UC San Diego, USA
- [Justin Buck](https://github.com/justinbuck), National Oceanography Centre, British Oceanographic Data Centre, UK
- [Juan Gabriel Fernández Pineda](https://github.com/JuangaSocib), SOCIB, Mallorca, Spain 
- [Emma Gardner](https://github.com/emmerbodc), National Oceanography Centre, British Oceanographic Data Centre, UK   
- [Daniel Hayes](https://github.com/glidermann), Cyprus Subsea Consulting and Services C.S.C.S. Ltd, Cyprus
- [John Kerfoot](https://github.com/kerfoot), Institute of Marine & Coastal Sciences, Rutgers University, New Jersey, USA
- [Callum Rollo](https://github.com/callumrollo), Voice of the Ocean Foundation, Sweden
- [Jennifer Sevadjian](https://github.com/jenseva), Southwest Fisheries Science Center Environmental Research Division, NOAA, USA
- [Sören Thomsen ](https://github.com/soerenthomsen), LOCEAN, ISPL, Sorbonne University, Paris, France,
- [Victor Turpin](https://github.com/vturpin), OceanGliders Technical Coordinator at OceanOPS, Brest, France

What to you think?

**Comment by callumrollo** [comment]
As Victor deduced, I used the order of github contributors as the basis for this first draft authorship list, as has been done in other Ocean Gliders Community documents like the [oxygen SOP](https://oceangliderscommunity.github.io/Oxygen_SOP/sections/authors_SOP_development_process.html). This misses people who have made contributions in meetings/by other methods than github commits though, so further edits and additions will be needed.

I'm happy with any additions, reordering or edits to the list

**Comment by glidermann** [comment]
I am happy with Victor's order, but please think if we are missing anyone...we should acknowledge (not as authors) OceanGliders, UG2, EGO for their encouragement and providing a forum to meet and discuss these issues in workshops, as well as specific projects (EuroSea?, AtlantOS?, GROOM II, ....) and their funding sources. Maybe an Acknowledgement section in history.adoc? or the format doc itself? Not urgent, but should be done at some point.

**Comment by emmerbodc** [comment]
Thanks for explaining this @vturpin. I can see the conversation has continued in #151 so i will close this issue.
