### ISSUE TITLE
Change "agency" with "institution"

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#153]
moderator: @OceanGlidersCommunity/format-maintainers

**Is your feature request related to a problem? Please describe.**
EGO, IMOS and IOOS format use the word "institutions" instead of "agencies" with the exact same meaning. In order to reduce the impact of users and DACs and facilitate the convertion of historical data sets to 0G1.0, could we use "institution" and "institution'r role", instead of "agencies" and "agencie's role" ?

**Is this related to a specific platform models**
No, this is applied in the global attribute.

**Describe the solution you'd like**
Use "institution" instead of "agencies".
Use "institution's role" instead of "agencie's role"

**Describe alternatives you've considered**
This could also impact slightly the reference table of the roles (e.g. "operating institution" instead of "operating agency", "funding institution" instead of "funding agency") But not necessarily.

**Additional context**

**Comment by glidermann** [comment]
Agreed, any volunteer to make the PR?

**Comment by vturpin** [comment]
I am happy to do that !

**Comment by castelao** [comment]
Since #154 was already merged, I guess we can close this one. @vturpin , if #154 didn't cover everything that you intended here, feel free to re-open it.
