### ISSUE TITLE
Final comparison between format and exemplar

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#158]
moderator: @OceanGlidersCommunity/format-maintainers

**Is your feature request related to a problem? Please describe.**
not a probleme but we need to make sure the exemplar cdl and the format description are align before release.

**Is this related to a specific platform models**
no

**Describe the solution you'd like**
assigne two person to review this issue

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by vturpin** [comment]
see #215

**Comment by emmerbodc** [comment]
can this be closed now? @vturpin

**Comment by emmerbodc** [comment]
I think based on recent meetings and pull requests we can close this issue.
