### ISSUE TITLE
RTQC_methodology - In global attribute or <PARAM>_QC attribute

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#170]
Moderator: @OceanGlidersCommunity/format-maintainers

Attributes related RTQC are in the global attribute section but also in the <PARAM>_QC variable attributes.

This is redondant.
If the same RTQC method is used for all the <PARAM>_QC, then it could stay in the global attribute. 
if the RTQC method can change from a <PARAM>_QC to another <PARAM>_QC then it should be in the <PARAM>_QC variable attributes. 

RTQC methodology is apply by DAC. DACs have there own documentation about all the QC they apply, so my suggestion would go to have RTQC related attribute on the global attribute.

**Comment by glidermann** [comment]
I agree with adding RTQC method in global attribute since (DAC or no DAC) QC methods are applied to whole file following a standard practice of some kind, documented in one place (to be referenced here in global attributes).

**Comment by castelao** [comment]
I think that there is a benefit in having the alternative of per variable or global. A global definition is referred to the whole dataset. If defined in the variable level that has precedence for that variable over the global.

Such approach would facilitate the process of transition to new technologies (sensors or QC procedures), as well as make it easier in the case of data aggregation.

**Comment by vturpin** [comment]
It was agreed yesterday that RTQC_method will be addressed as an attribute of <PARAM_QC>. As some DACs apply different method depending on the parameter.

**Comment by vturpin** [comment]
we will close this issue when PR submitted
