### ISSUE TITLE
Ambiguity in use of the term "platform" in the format specification 

### ISSUE THREAD

**Issue by justinbuck** [OceanGlidersCommunity/OG-format-user-manual#174]
Proponent(s):

Moderator: @OceanGlidersCommunity/format-maintainers

**Describe the error**
HI Kimmo,

We have example earlier version of OG1.0 up on our ERDDAP that you can explore:
-	https://linkedsystems.uk/erddap/files/Public_OG1_Data_001/
Looks like you have found an ambiguity in the format platform and platform_name are two different entities
-	Platform is the L06 term for the type of oceanographic platform for OceanOps and the GOOS
-	Platform_name is the name of the glider, currently groups use names like Kraken etc, as the fleets grow it may just be a version of the serial (our navy already do this) like unit_123 or SG57.
I’ll raise this as an issue in the repo, thank you for highlighting this.
Justin

From: Tikka Kimmo (FMI) @kimmotikka 

Hi Justin,  
I tried to make a file with the metadata needed to OG1.0-files. 
In the page https://oceangliderscommunity.github.io/OG-format-user-manual/#ProgramNetworkSite-example
There are some question marks for me. An example file would certainly help. 

One specific question: In the beginning there is definition and example of ”platform”, referenced to vocab https://vocab.nerc.ac.uk/collection/L06/current/ and example "sub-surface gliders” as of the vocab. 
Anyhow, in the examples part is given
Example 1: platform (i.e. glider mission): kraken_20210205
So, I think either should be changed!?
Regeards, Kimmo

**Comment by vturpin** [comment]
Thanks Kimmo, this ambiguity will be removed from the current version of the user manual and exemplars by release. 
Currently, there are discrepencies between user manual and exemplar that are under our radar and waiting for the approval of pull request.

**Comment by vturpin** [comment]
The current definition of platform is (comming from ACDD 1.3).

![image](https://github.com/OceanGlidersCommunity/OG-format-user-manual/assets/79571123/af27a591-52a8-4db5-9844-25119012522c)

Using `name` in this definition may be misleading. We could explain better that name refers in fact to a `type` of platform. We could also add in the last colum that this must be a fixed value.

We could add in the column for each attribute the following prefixes:

- f. = format
- ex. = exemplar
- f.v. = fixed value
To clarify the meaning of the information in the cell.

**Comment by vturpin** [comment]
We will go for a new version of the platform definition: "Category of the platform that supported the sensor data used to create this data set or product. This falues is commin to any OceanGliders data sets and define by the following vocabulary: 
http://vocab.nerc.ac.uk/collection/L06/current/27/"

Note that the reference to "platform_type" should be removed from the table on control vocabularies as the format never refer to "platform_type".
