### ISSUE TITLE
Review ASCIIDoc content

### ISSUE THREAD

**Issue by castelao** [OceanGlidersCommunity/OG-format-user-manual#18]
Review content comparing with the original Google Doc. Don't worry about the format/style at this point. The goal here is: did we leave anything behind?

**Comment by castelao** [comment]
@vturpin , was the latest version of the document public? If so, could you add the link to that document here? Please, verify if it is not open for editing by anyone before posting the link here. Thanks!

**Comment by soerenthomsen** [comment]
i think the latest google doc version is linked here or?
https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/Toward_the_evolving_OG_format_manual.md

I can only see the document there and not edit, so all good.

Happy to start to compare the content of both versions if @vturpin confirms it is the right version.

**Comment by soerenthomsen** [comment]
@castelao I reviewed the content of both documents. looks good, not content missing.

I found small space/typos/formating issues which I noted down and will address in a separate pull-request at a later stage when the ongoing pull-requests are closed to avoid conflicts.

**Comment by soerenthomsen** [comment]
Sure will do that!

**Comment by justinbuck** [comment]
In BODC are using the document on github as a the basis for generating test OceanGliders files in coming months

**Comment by castelao** [comment]
@justinbuck , could you confirm that we have all the content from the original Google Doc moved to [here](https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/OG_Format.adoc)? I believe that @vturpin is away. If you're busy, don't worry, we can wait for @vturpin .

**Comment by justinbuck** [comment]
@castelao  Just did a quick check and it looks like all the original OG1 document content has moved across.
When the other documents e.g. vocabularies are migrated we will need update the current link sin the documentsion.

**Comment by justinbuck** [comment]
@soerenthomsen I have checked this to the merge request can go ahead

**Comment by soerenthomsen** [comment]
Thanks @justinbuck can you please always link the pull request you referring to here. I assume you refer to #27 right?

**Comment by soerenthomsen** [comment]
@justinbuck could you also confirm that all open discussions from the gdoc are moved over here?

**Comment by justinbuck** [comment]
To my knowledge any open conversations are now on github, I added a missing one yesterday.

**Comment by soerenthomsen** [comment]
Ok i merged #27 and will close this issue now.
