### ISSUE TITLE
OG1.0 vocab review: platform_maker

### ISSUE THREAD

**Issue by clayton33** [OceanGlidersCommunity/OG-format-user-manual#203]
@OceanGlidersCommunity/og1-0-vocab-reviewers

In the `Table of Controlled variables`, the `OceanGliders reference name` `platform_maker` listed `Collection name` links to the `NERC L35` collection. But the `platform_maker.md` file has conflicting information. It's a mix of links to `EDMO` and the `NERC B75` collection (see in `definition` column), I added the `NERC B75` link in a new column, if it was missing and it exists.

| platform_maker | definition | NERC B75 |
|:----- |:----- |:----- |
| Teledyne Webb Research | http://vocab.nerc.ac.uk/collection/B75/current/ORG01077/ | |
| Kongsberg Maritime AS | http://vocab.nerc.ac.uk/collection/B75/current/ORG00360/ | |
| Scripps Institution of Oceanography | https://edmo.seadatanet.org/report/1390 | https://vocab.nerc.ac.uk/collection/B75/current/ORG00134/ |
| Alseamar | https://edmo.seadatanet.org/report/5241 | |
| University of Washington | https://edmo.seadatanet.org/report/3839 | in NERC B75, 3 options, APL - https://vocab.nerc.ac.uk/collection/B75/current/ORG00202/, Aquatic and Fishery - https://vocab.nerc.ac.uk/collection/B75/current/ORG01019/, Oceanography - https://vocab.nerc.ac.uk/collection/B75/current/ORG00142/ |
| IRobot | http://vocab.nerc.ac.uk/collection/B75/current/ORG01747/ |  |
| Hydroid Inc. | http://vocab.nerc.ac.uk/collection/B75/current/ORG01760/ | |
| Huntington Ingalls Industries | https://edmo.seadatanet.org/report/5678 | |
| Hefring Engineering | https://www.hefring.com/ | |

**This discrepancy brings up a question :** 

Which vocabulary collection name is the correct one, `NERC L35`, `NERC B75`, or `EDMO` ? To help, here are the description for the two NERC collections : 

- `NERC B75` (https://vocab.nerc.ac.uk/collection/B75/current/) description : Up-to-date names and addresses for organisational entities referenced in BODC systems.
- `NERC L35`  (https://vocab.nerc.ac.uk/collection/L35/current/) description : A collection of terms which denote the manufacturers or developers of devices (includes manufacturer and/or developer collaborations).

**One other question :**

Should the `OceanGliders reference name` be `platform_make` ? A very parallel example to gliders is how cars are usually referred to (at least here in North America, I don't know if it is different in other parts of the world) as the make and model, not the maker and the model.

**Comment by vturpin** [comment]
Well spotted. Thanks.
I will check. I think we will use NERC (don't know wich one yet) as the collection. It make more sens because the list is very limited. 

With regard to 'platform_make and model' or 'platform_maker' I don't have strong opinion really, but the advantage I see using maker is that we align with other ocean platforms vocab like Argo or drifting buoys. Which is in my opinion an advantage on the long run.

**Comment by emmerbodc** [comment]
for the platform_maker and sensor_maker we are now referencing the L35 collection in the vocab guidance. Can this issue be closed?
