### ISSUE TITLE
Mnaul changes to finish OG 1.0

### ISSUE THREAD

**Issue by justinbuck** [OceanGlidersCommunity/OG-format-user-manual#207]
@callumrollo stretd notes on the changes needed base don the meeting on 14th May 2024.

- The second non ACDD institution needs to change to contributing_institutions (along with associated  id, vocabulary sections), need example for each term too.
- data_url to be reviewed.

Vocabs
Institution role vocabulary needs defining.

We got as far a data_url in global attributes.

**Comment by callumrollo** [comment]
Here's the additional changes I made notes of:


### head section
- add ocean gliders link from icon
- intro para: it is envisaged that the format will continually evolve as the last sentence. Drop the word "finally"
- add link to https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/governance.md but remove the vocab section
- Header authorship, sub heads author and contributors. add callum and jennifer to authors
- want to acknowledge NERC and other projects. Justin to add
- embed some links in the background
- link to vocabularies page in the OG1.0 general conventions
- OG1.0 defines some variables (in this document). Others can be included in OG1 files (e.g. technical intermediate ones) but are not defined by OG
- interpolation methodologies etc. are determined elsewhere in e.g. SOPs and should be linked. Where applicable, follow community best practice
- change GPS to geolocation
- get rid of line "a list of mandatory metadata"
- remove uri mtm and incorporate into other uri/sop para
- 3 recommendation levels remote "for attributes"

DOi management
- remove GDAC line
- Line above "recommend to reference source providers"

OG1 naming convention
- just be one line: platform_name _ start_date _ data_mode
- add an extra explainer underneath that R is nrt. Replace R with <data_mode>
- Do CF 1.10 everywhere, not 1.8
global attrs
- acdd 1.3 where possible https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3
- for the last column, have every single one start with "example:" or "fixed value:" or "format:"
- in e.g. platform_vocabulary  this is an example
- move platform vocab list to platform_vocab item row description
- add a simple explanation of what vocabulaires are and link that the first time vocabs are referenced 
- use platform serial in all important stuff. This is defined as e.g. sg001


I'll put in a gib PR this afternoon fixing them

**Comment by callumrollo** [comment]
Here is a todo list following from our meeting yesterday. The majority of the items are addressed in PR #208 so have been ticked off. Others have tagged issues/delegated responsible authors

### head section
- [x] Add ocean gliders link from icon

### methodology
- [x] intro para: it is envisaged that the format will continually evolve as the last sentence. Drop the word "finally"
- [x]  Add link to https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/governance.md 
- [ ] Remove the vocab section from governance #205 
### authorship

- [x] Header authorship, sub heads author and contributors. add callum and jennifer to authors
- [ ] want to acknowledge NERC and other projects. @justinbuck

### background

- [ ] embed some links in the background
- [x] link to vocabularies page in the OG1.0 general conventions
- [x] OG1.0 defines some variables (in this document). Others can be included in OG1 files (e.g. technical intermediate ones) but are not defined by OG
- [x] interpolation methodologies etc. are determined elsewhere in e.g. SOPs and should be linked. Where applicable, follow community best practice
- [x] change GPS to geolocation
- [x] get rid of line "a list of mandatory metadata"
- [x] remove uri mtm and incorporate into other uri/sop para
- [x] 3 recommendation levels remote "for attributes"

### DOI management

- [x] remove GDAC line
- [x] Line above "recommend to reference source providers"

### OG1 naming convention

- [x] just be one line: platform_name _ start_date _ data_mode
- [x] add an extra explainer underneath that R is nrt
 
### global attrs

- [x] Do CF 1.10 everywhere, not 1.8
- [x] acdd 1.3 where possible https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3
- [x] for the last column, have every single one start with "example:" or "fixed value:" or "format:" in e.g. platform_vocabulary  this is an example
- [x] move platform vocab list to platform_vocab item row description
- [ ] add a simple explanation of what vocabularies are to the vocabularies document @emmerbodc #206 
- [x] link that the first time vocabs are referenced 
- [x] use platform serial in all important stuff. This is defined as e.g. sg001
- [ ] The second non ACDD institution needs to change to contributing_institutions (along with associated id, vocabulary sections), need example for each term too. @justinbuck
- [ ] data_url to be reviewed. @vturpin

### Vocabs  

- [ ] Institution role vocabulary needs defining. @emmerbodc

**Comment by callumrollo** [comment]
all addressed or moved to #215
