### ISSUE TITLE
The TRAJECTORY variable

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#21]
Status of this discussion, keep the manual as it is.
Use underscore to separate <platform_code> to <start_date> : 
TRAJECTORY = <platform_code>_<start_date>

**Comment by justinbuck** [comment]
Underscores are the recommended delimiter in the ERDDAP documentation and the primary purpose for inclusion of the trajectory variable is for inclusion of the data in ERDDAP so underscores are the preference of Mark Hebden and myself.

**Comment by castelao** [comment]
This is a good example for #30. What is the criterion to close this issue? What do we need to accept this decision?

**Comment by soerenthomsen** [comment]
Agree with @castelao good example. Also for me it is a challenge that not every author is on GitHub for now.

**Comment by justinbuck** [comment]
I think agenda item one for when @vturpin is back is to agree the process for decision making

**Comment by vturpin** [comment]
Shall we have a more formal/official reviewers team now that the Github is running ? 
5 to 10 peoples that will be in charge of the reviewing the issues and pull request, discussing it internally and agree or not on the evolution of the format? At least we should offer each DAC the opportunity to have one representative in the reviewers team.
Today, we are 5 to do this job, Gui, Justin, Dan, Soeren and myself, but I do not think Soeren aims to continue in the data management. And I think we should probably be more than 4...

Regarding the decision making, I see two options : voting or unanimity. Today to accept a PR you need two reviewers to validate.
Unanimity may lead to inaction.
Voting is good but we need to have enough vote to be valid. 

Regarding this particular issue : 
Justin, me, Dan agree on using underscore instead of Hyphen in the trajectory variable name. 
I don't know what is your opinion Gui but let's consider you prefer "-" (just for the example). 

If we do voting, we use "_". If we do unanimity then we are stuck until we all agree...

What do you think ?
