### ISSUE TITLE
No Lower/upper case rule for variables

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#213]
Upper case for variable came from the historical format EGO (and maybe others, not sure) and is similarly apply on Argo data format.

From @castelao comment in #191 , seconded by @callumrollo this is very "old fashion" style and should be remove from the OG1.0 format.

Knowing this, I don't see anymore reason for maintaining a rule on case for variable. I may not have all the perspectives on this.

If it makes the format looking better with no impact. I am in favor of such change. In terms of PR, this is only removing the bullet point refereing to upper case in the general convention. No need to change to lower case in the text is it ?

**Comment by jenseva** [comment]
I am in favor of lower case as well and agree the upper case appears outdated. Personally, I see upper case letters as SHOUTING. If there is a consensus that lower case is okay, I recommend adding a note that lower case is okay and offering an example that shows lower case names. I believe the vocabulary shows the  names in upper case which could be confusing.

**Comment by callumrollo** [comment]
Yeah I have been guided by the OG1 vocabulary over at https://vocab.nerc.ac.uk/collection/OG1/current/

Maybe this is a call for @emmerbodc and the vocab team?

**Comment by vturpin** [comment]
PR #233
