### ISSUE TITLE
More changes to the format from today's meeting

### ISSUE THREAD

**Issue by callumrollo** [OceanGlidersCommunity/OG-format-user-manual#215]
I'll work through this list tomorrow and tag others if help is needed

### Global attributes

- [x] add NERC to the acknowledgement
- [x] data_url is tricky? Set by DAC? change to highly desirable: Link to where the datafile is hosted
- [x] #216
- [x] do not make doi fields mandatory - do highly desirable and have an example "n/a" if there is none 
- [x] 2nd institution this to be "contributing_institutions" the link to contoibuting_institutions_vocabulary should be changed. Want to link to W08. Change wording to "Operator is mandatory"
- [x] downgrade data_url to highly desirable
- [x] example in rtqc "No QC applied"
- [x] date_created and start_date to both be the same with **ex:** date
- [x] line "some examples provided in": remove

### location varaibles:
- [x] remove redundancy in first two lines
- [x] get rid of note on legacy for EG
- [x] add a fourth column for examples etc.

### along track variables

- [x] again get rid of first 2 lines rreddundancy
- [x] get rid of interepolation methodology vocabulary. Add notes that these are suggested?
- [x] get rid of line on interpolation best practices
- [x] add a fourth column for examples etc.
- [x] platform_model add link to vocabulary B76
- [x] reorder items to make more sense. mandatory up top
- [x] seaglider should be sg not sea, make it unit_. 
- [x] Make it all ex: not eg.
- [x] platform name remove that extra text and make it just local nickname
- [x] ICES platform code add vocab
- [x] Platforrm make B75

### deployment info
- [x] remove lost bullet point above field comparison info

### hardware info
- [x] battery pack e.g. 2 * 12 volt battery*
- [x] when mandatory must link to a real controlled vocab when not madatyory can just link to a list on github

### phase

- [x] update link to phase to ponit to main branch version of vocab, not victors
- [x] phase vocab shoudl link to victor's list
- [x] cut line about best practices
- [x] cut line about phase mandatorry
- [x] remove phase calc method doi
- [x] PHASE_QC add commas to flags
- [x] delete from vocab collections to best practices (don't delete best practices!)

### sensor

- [x] simplify formatting of attributes for SENSOR
- [x] vocab is L05
- [x] add a fill value
- [x] fill out an example column

Reached up to end of geophysical variables

**Comment by emmerbodc** [comment]
@callumrollo do we need this task 
'add a fill value'
for sensor information

**Comment by vturpin** [comment]
completed
