### ISSUE TITLE
 Item: wmoid

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#22]
"wmoid' and 'WMO_IDENTIFIER' is the same information stored in a global attribute and a variable

After checking in the OceanSITES and ARGO format, it appears that "wmoid" is a global attribute for OceanSITES under "wmo_platform_code" and a variable in ARGO under "PLATFORM_NUMBER".

**Comment by vturpin** [comment]
comment from Gui : 

"I have no strong opinion on this, but why not follow Argo? I think that it's OK to break with Argo standard, but be able to seamlessly merge Argo and glider data is a bonus. I feel like it should be worth it whenever we break standard with Argo.

WMO_IDENTIFIER as a variable also allows merging different platforms in one single file, such as a fleet from the same experiment."

**Comment by vturpin** [comment]
comment from Justin

"I think it is a broader question than Argo, with OceanSITES and IOOS using attributes Argo may be in the minority on this one."

**Comment by gkrahmann** [comment]
Hi all,
should this be merged with the issue
Variables versus attributes...       ?

There I just added my 5c

**Comment by justinbuck** [comment]
On OceanSITES, which is the most recent format it is confirmed as an attribute: http://www.oceansites.org/docs/oceansites_data_format_reference_manual.pdf
This is the most recent GOOS format to be signed of by GOOS too.

**Comment by vturpin** [comment]
I would suggest "WMO_IDENTIFIER" as a variable for the following reasons.
as Gui said, WMO_IDENTIFIER as a variable also allows merging different platforms in one single file. This principle is driving the way we shape this format since the begining I think.
Flowing Argo is ok. I see many benefit in this.
We can already identify the platform in the file naming convention (see #51)

I've made a pull request  #53 in that sense. If addopted, we will close this issue.

**Comment by justinbuck** [comment]
I have no preference so long as it is in the file. Care is needed in how it is used as the application of WMO identifiers for gliders is different in gliders to Argo (we need to review observing systems beyond Argo as part of this process). In Argo every deployment of a float has a new WMO id, gliders keep their WMO for their life time (more akin to ships and moorings). Consequently, multiple glider deployments has have the same WMO and is cannot be used to uniquely identify deployments on the GDAC, the trajectory ID offers this capability.

**Comment by glidermann** [comment]
#53 approved so closing this issue: using wmo id as a variable makes merging deployments cleaner. It remains mandatory.
