### ISSUE TITLE
add exemplar column for sensor variable and platform, telecom, field, deployment and hardware information

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#222]
moderator: @OceanGlidersCommunity/format-maintainers

I would like to add an exemplar column for the sensor variable. This would facilitate the understanding of the variable attributes it think.

same for platform, telecom, field, deployment and hardware information

**Comment by vturpin** [comment]
#233

**Comment by callumrollo** [comment]
Could  you add exemplar columns for telecom, field deployment and hardware? I don't have a good handle on what those should look like

**Comment by vturpin** [comment]
If your talking about FIELD_COMPARISON_REFERENCE ? @emmerbodc should be able to provide exemplar.

For Hardware : 
:battery_type = "lithium rechargeable"
:battery_type_vocabulary = "https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/vocabularyCollection/battery_type.md"
:battery_pack = "2X12 12V battery"
:glider_firmware_version = "V1.3.22"
:landstation_version = "dockserver V3.42"

For TELECOM
:telecom_type = “iridium”
:telecom_type_vocabulary = “https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/vocabularyCollection/telecom_type.md”
:tracking_system = "gps, accoustic"
:tracking_system_vocabulary = “https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/vocabularyCollection/tracking_system.md, https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/vocabularyCollection/tracking_system.md”

Can I edit your PR ? Or wait until it is accepted to submit another one with those exemplars ? Or you can take those and add it to PR. Doesn't matter to me. Let me know what is the easiest ?

**Comment by vturpin** [comment]
I'll do that today since pending PR has been accepted

**Comment by emmerbodc** [comment]
I don't have an example that I have published but i think the idea if i remember well was to have a DOI to reference comparison data such as a CTD dataset.

**Comment by emmerbodc** [comment]
shall we close this for now and look back at field comparison in the future?

**Comment by vturpin** [comment]
done

**Comment by vturpin** [comment]
PR #233
