### ISSUE TITLE
Consider updating latitude and longitude variables long name

### ISSUE THREAD

**Issue by jenseva** [OceanGlidersCommunity/OG-format-user-manual#237]
Proponent(s): @jenseva 

Moderator: @OceanGlidersCommunity/format-maintainers

I noticed that the long name for latitude and longitude variables looks incorrect.

It currently is spec'd as, "latitude of each measurement and GPS location", but this is not true for underwater gliders. I recommend using something like: "Estimated Subsurface Latitude of Each Measurement" instead.

**Platforms affected**
All.

**Additional context**
I've started including a comment attribute on the subsurface position variables attempting to describe the inaccuracy and that these latitudes are estimated based on surface GPS measurements before and after the dive.

**Comment by emmerbodc** [comment]
They do also include the GPS locations so I think we should keep that part in the long name unless others disagree.

**Comment by vturpin** [comment]
I do agree with Emma, measurement are also made during surfacing. So we need to make clear this is not only estimated by also GPS.

I also think the definition of Jen is more precise.

So i will suggest a mix of both ?
 
Would  "Estimated Subsurface Latitude of Each Measurement and GPS location" be acceptable ?

**Comment by emmerbodc** [comment]
agreed in meeting yesterday to follow vocabulary preferable label for the long name string.

**Comment by vturpin** [comment]
Yes what Emma suggest will solve that case.
vocab pref long name is "Latitude north (WGS84)" 
see definition: http://vocab.nerc.ac.uk/collection/OG1/current/LAT/ 
And we will link this variable to the vocab.

This definition doesn't bring any confusion I think. It can be Latitude from GPS or calculated latitude doesn't mater here. Is it acceptable for you @jenseva ?

@emmerbodc are you in charge of this PR ?

Does it sound good for you @jenseva

**Comment by jenseva** [comment]
Great, thank you for clarifying @vturpin!

**Comment by jenseva** [comment]
Oops, I'll wait to close this, so you can have it for your resolution/PR.

**Comment by callumrollo** [comment]
Thanks for raising @jenseva! Resloved in #252
