### ISSUE TITLE
format attribute for trajectory variable?

### ISSUE THREAD

**Issue by jenseva** [OceanGlidersCommunity/OG-format-user-manual#238]
Proponent(s): @jenseva 
Moderator: @OceanGlidersCommunity/format-maintainers

**Describe the error**

In the manual for variable TRAJECTORY
:format is listed in the variable attributes column, appearing as an attribute but I think this may have been meant to be part of the descriptive text below and not an attribute?

I can adjust and make PR if there is agreement.

**Comment by emmerbodc** [comment]
Yes it is, please make a PR
Thank you

**Comment by vturpin** [comment]
Close with PR #243
