### ISSUE TITLE
Links to the NERC vocabulary server need to be https rather than http

### ISSUE THREAD

**Issue by justinbuck** [OceanGlidersCommunity/OG-format-user-manual#24]
Hi,
The links to the NVS are currently listed as http. It is best practice in security to use https so could the NVS links in the specification be updated to https to enable this please?
Thanks,
Justin

**Comment by justinbuck** [comment]
@castelao is it possible to update the main document with this please

**Comment by soerenthomsen** [comment]
@justinbuck I made a pull-request to make these changes in the document. After @castelao reviewed we can merge it.

**Comment by soerenthomsen** [comment]
This can be closed now.
