### ISSUE TITLE
coordinates attributes

### ISSUE THREAD

**Issue by jenseva** [OceanGlidersCommunity/OG-format-user-manual#240]
moderator: @OceanGlidersCommunity/format-maintainers

:coordinates variable attributes
The order of the coordinates is not what I am used to. I usually see them ordered as time, longitude, latitude, depth. Is there is another spec you are following.

Also, it is not clear if the coordinate names are flexible. I have multiple coordinate systems in my files. The depth averaged variables get different coordinates from the profile data. I suggest clarifying this in the description and maybe providing an example or link to example with multiple coordinate options.

I'm happy to update the doc if there is agreement.

**Is this related to a specific platform models**
no

**Comment by vturpin** [comment]
Sorry, this is unclear to me to the multiple coordinates.

Does this general convention :`"OG1.0 defines some variables and definitions, as described in this document. Other types of measurements (e.g. intermediate parameters, technical measurements, other variables) not framed by OG1.0 can be included in OG1.0 data files. No control will be applied to those measurements."`  gives you enough flexibility to add other type of coordinates?

It aim to leave DAC freedom to add any variable to the data set.
