### ISSUE TITLE
DEPTH missing?

### ISSUE THREAD

**Issue by jenseva** [OceanGlidersCommunity/OG-format-user-manual#241]
Proponent(s): @jenseva 
Moderator: @OceanGlidersCommunity/format-maintainers

**Describe the error**
It looks like details for a depth variable are missing from the documentation. This variable doesn't fit into the PARAM section as it is one of the coordinate variables. Also, this var has attributes that are unique to it in the spec.

**Example**
Here are some attributes that I think should be documented:
  :_CoordinateAxisType = "Height";
  :_CoordinateZisPositive = "down";
  :axis = "Z";
  :positive = "down";
  :reference_datum = "sea-surface";

**Potential solution**
Add a description for this variable somewhere and specify the attributes for it. 

**Platforms affected**
All

**Comment by emmerbodc** [comment]
Thanks Jen. There is a DEPTH parameter in the OG1 vocab collection so at the moment its being recorded under the same attributes as any other PARAM variable 

e.g in example file

float GLIDER_DEPTH(N_MEASUREMENTS) ;
		GLIDER_DEPTH:_FillValue = NaNf ;
		GLIDER_DEPTH:long_name = "Depth (spatial coordinate) relative to water surface in the water body" ;
		GLIDER_DEPTH:units = "m" ;
		GLIDER_DEPTH:standard_name = "" ;
		GLIDER_DEPTH:vocabulary = "https://vocab.nerc.ac.uk/collection/OG1/current/DEPTH/" ;
		GLIDER_DEPTH:ancillary_variables = "GLIDER_DEPTH_QC" ;
		GLIDER_DEPTH:sensor = "INSTRUMENT_DATA LOGGERS_sg558" ;

If we want additional attributes for this parameter, I guess we would need to have to mention this specifically somewhere else.

**Comment by vturpin** [comment]
Indeed attribute of depth should/could be discussed?
I'll tag this issue as 1.X then.

**Comment by emmerbodc** [comment]
agreed in meeting yesterday to add depth in the manual to the co-ordinates section. I'll close this issue when this PR request goes in

**Comment by emmerbodc** [comment]
closing as depth is now added in co-ordinates section
