### ISSUE TITLE
data type placement inconsistency within manual 

### ISSUE THREAD

**Issue by emmerbodc** [OceanGlidersCommunity/OG-format-user-manual#246]
Hello, I noticed the data type is a little inconsistent throughout the manual
Sometimes we display under the variable name like
data type: double
and others it is included within the variable attributes

**Comment by emmerbodc** [comment]
agreed in meeting yesterday to add in data type underneath variable. Issue will close when PR put in.

**Comment by callumrollo** [comment]
resolved in #251
