### ISSUE TITLE
Alignment of terminology with ACDD

### ISSUE THREAD

**Issue by justinbuck** [OceanGlidersCommunity/OG-format-user-manual#26]
Issue:
The definition of "network" needs to be improved to avoid misunderstanding of it meaning in the context of OG. Program , project , network and even sites are concepts that are regularly misinterpreted or shoehorned by users.

We will also add examples (later in the document) to identify the difference between concepts that seems similar at first sight : program, project, network, site.

Status:
•	current definition : 
The name of the networks this deployment is part of. Multiple networks can be separated by commas. 

•	OceanOPS definition of network: 
A network is a grouping of platforms, crossing the boundaries of the program. It is usually virtual and represents a common effort or way to measure data. It can represent a mutualized scientific/geographical goal (array), a platform class, or logistical/funding/etc. approach.

Proposal:
Use the following definition : 
A network is a grouping of platforms, crossing the boundaries of the program. It can represent a mutualized scientific objective (Boundary Ocean Observing Network, OceanGliders Storms), a geographical focus (MARACOOS, MOOSE, PAP), an array (OSNAP, CUGN), a project (MOSES, Alter Eco).

**Comment by justinbuck** [comment]
Hi, Logging his one here as I am not sure it is resolved. It is important that we follow the ACDD definitions of such terms as failure to do so mean that the file is not ACDD complaint and we cannot strictly list ACDD within the conventions (because we have unconsent definitions). I have also raised the alignment of OceanOps terms with ACDD and other vocabularies like EDIOS within the OCG metadata harmonisation work.

**Comment by vturpin** [comment]
I have submitted a pull request #52 (copy paste of the definition of Justin).

**Comment by castelao** [comment]
@justinbuck , is your proposal well covered by #52? If not, could you address there what is missing so we have a concrete suggestion as a PR. Once you're happy with the proposal there, we should close this issue here. We are creating too many redundant entry points. It will help us to converge those.

**Comment by vturpin** [comment]
@justinbuck Could you check #52 and let us know if this is ok with you ? Then @castelao could also accept #52 and merge.

**Comment by castelao** [comment]
Let's close this issue and move all the discussion to PR #52. @justinbuck comments will keep accessible.
