### ISSUE TITLE
Use of OG1:TCPUCHLA "temperature sensor mounted on a CPU" for sensors other than flourometers

### ISSUE THREAD

**Issue by callumrollo** [OceanGlidersCommunity/OG-format-user-manual#263]
Moderator: @OceanGlidersCommunity/format-maintainers

Crossover vocabularies Issue

**Motivation**: We have a variable that represents the internal temperature of a PAR sensor. We need to reference the correct OG1 concept for this variable.

**Issue description** OG1 has the concept [OG1:TCPUCHLA](https://vocab.nerc.ac.uk/collection/OG1/current/TCPUCHLA/) with the label "Thermistor signal from backscattering sensor". The label and concept name, which includes CHLA, indicate that this concept is solely for the internal temperature of backscattering/CHLA sensors. However, OG1:TCPUCHLA has the linkage "Same As" to [P01:TCNTICPU](https://vocab.nerc.ac.uk/collection/P01/current/TCNTICPU/).  P01: TCNTICPU has the label "Raw signal (counts) of CPU temperature determination" and the Definition "The raw analogue-to-digital converter output from a temperature sensor mounted on a CPU that is a component part of an instrument or sensor.". This suggests to me that we can use P01: TCNTICPU for the internal temperature of our PAR sensor, as it covers broadly instruments and sensors.

**Questions**

1. Can we use OG1:TCPUCHLA as the reference concept for the internal temperature of a PAR sensor, despite it specifying "backscattering sensor"? Or should we use P01: TCNTICPU? Or do we request a new OG1 term?
2. Is it the case that P01: TCNTICPU is "Same As" OG1:TCPUCHLA, given that the latter is textually more restrictive (flourometers only)?
3. If so, how flexible is the "Same As" linkage? 

This Issue has been crossposted to NVS:P01 https://github.com/nvs-vocabs/P01/issues/271

**Comment by emmerbodc** [comment]
discussed in vocab meeting 06/09/24
Agreed to change alternative label to TEMP_CPU_FLUOR, the pref label to match R03 and the P01:TCNTICPU will be changed from same as to related. A new OG1 term will be created for CPU from radiometer 
Action @danibodc

**Comment by danibodc** [comment]
Updates to [OG1:TCPUCHLA](https://vocab.nerc.ac.uk/collection/OG1/current/TCPUCHLA/) have been made and will be live on the NVS from tomorrow morning.

**Comment by danibodc** [comment]
Proposed new term for internal temperature of a radiometer (for PAR sensors) - feedback welcome:

**Proposed identifier:**
TCPURADP

**Proposed preferred label:**
Thermistor signal from radiometer

**Proposed alternative label:**
TEMP_CPU_RADIOM

**Proposed definition:**
The raw analogue-to-digital converter output from a temperature sensor mounted on a CPU that is a component part of a radiometer.

**Comment by danibodc** [comment]
This term has now been loaded and will be live on the NVS from tomorrow morning. 
TCPURADP	Thermistor signal from radiometer
