### ISSUE TITLE
 New OG1 vocabulary term - Downwelling irradiance at 532 nm 

### ISSUE THREAD

**Issue by callumrollo** [OceanGlidersCommunity/OG-format-user-manual#264]
Same as  #257 but for a different wavelnegth

Request for a new OG1 term for downwelling irradiance at 532 nm, measured from a Satlantic OCR504 downwelling irradiance sensor. Measures irradiance intensity at 4 factory set wavelengths (380, 490, 532 nm + PAR) in μWcm-2nm-1.

Proposed identifier: ED532
Proposed preferred label: Downwelling irradiance at 532 nanometers
Proposed alternative label: DOWN_IRRADIANCE532
Proposed definition: The vertical component of light at 532 nm wavelength travelling downwards.

This would be mapped to P06 units term UWNM- Watts per square metre per nanometre (https://vocab.nerc.ac.uk/collection/P06/current/UWNM/) to maintain consistency with existing unit mappings for similar irradiance terms in OG1.

It exists in P01 as https://vocab.nerc.ac.uk/collection/P01/current/RXUD532E/

**Comment by danibodc** [comment]
Thanks @callumrollo this term has now been loaded and will be live on the NVS from tomorrow morning at https://vocab.nerc.ac.uk/collection/OG1/current/ED532/.

**Comment by emmerbodc** [comment]
agreed in vocab meeting so closing ticket
