### ISSUE TITLE
Request for OG1 vocab term: Concentration of phycoerythrin

### ISSUE THREAD

**Issue by callumrollo** [OceanGlidersCommunity/OG-format-user-manual#265]
Request for a new OG1 term for concentration of phycoerythrin

Proposed identifier: PHYC
Proposed preferred label: Concentration of phycoerythrin {CAS 11016-17-4} per unit volume of the water body [dissolved plus reactive particulate phase] by in-situ fluorometer
Proposed alternative label: PHYCOERYTHRIN
Proposed definition: Quantity or mass of the specified analyte in a unit volume of an unfiltered sample of fresh or salt water.

It exists in P01 as http://vocab.nerc.ac.uk/collection/P01/current/PHYCSPP5/

There are already matched terms in P01 and OG1 for the corresponding raw signal vale"Phycoerythrin signal from fluorescence sensor"

http://vocab.nerc.ac.uk/collection/OG1/current/FLUOPHYC/
http://vocab.nerc.ac.uk/collection/P01/current/FVLTPELS/

They have the "Same As" mapping between them

**Comment by emmerbodc** [comment]
agreed in vocab meeting 06/09/24
Action @danibodc

**Comment by danibodc** [comment]
This term has now been loaded and will be live on the NVS from tomorrow morning:

PHYC - Concentration of phycoerythrin by fluorometer
