### ISSUE TITLE
Request for OG1 vocab term: concentration of phycocyanin

### ISSUE THREAD

**Issue by callumrollo** [OceanGlidersCommunity/OG-format-user-manual#268]
Request for a new OG1 term for concentration of phycocyanin. Very similar to the approved term PHYC for phycoerythrin described in #265

Proposed identifier: PHYCOCYANIN
Proposed preferred label: Concentration of phycocyanin per unit volume of the water body [dissolved plus reactive particulate phase] by in-situ fluorometer
Proposed alternative label: phycocyanin_concentration
Proposed definition: Quantity or mass of the specified analyte in a unit volume of an unfiltered sample of fresh or salt water.

**Comment by danibodc** [comment]
Thanks @callumrollo, to align with existing terms in OG1 I would propose the following:

Proposed identifier: PHYCOCYANIN
Proposed preferred label: Concentration of phycocyanin by fluorometer
Proposed alternative label: PHYCOCYANIN
Proposed definition: Phycocyanin concentration per unit volume of fresh or salt water.

I would then create a mapping to P01. A new P01 term would need to be created which would have a preferred label as you describe above:
Concentration of phycocyanin per unit volume of the water body [dissolved plus reactive particulate phase] by in-situ fluorometer.

The P06 units associated with the phycoerythrin parameter are Nanograms per litre - is this appropriate for this phycocyanin parameter too?

**Comment by callumrollo** [comment]
Sounds good to me! Thanks Dani

**Comment by danibodc** [comment]
We will actually need to create the associated P01 term with a matrix of 'water body [particulate >unknown phase]' as opposed to 'water body [dissolved plus reactive particulate phase]'. This was an error on our part, and all pigments should use the former. We will look to discuss this further in our next monthly NVS meeting and will most likely update the preferred label of https://vocab.nerc.ac.uk/collection/P01/current/PHYCSPP5/.

**Comment by danibodc** [comment]
This term is now live on the NVS:
https://vocab.nerc.ac.uk/collection/OG1/current/PHYCOCYANIN/

**Comment by callumrollo** [comment]
Thanks Dani!
