### ISSUE TITLE
"DISSOLVED_OXYGEN_SENSOR" sounds very unspecified

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/OG-format-user-manual#40]
This is keep track of the fact that in OG_Vocabulary.adoc a "DISSOLVED_OXYGEN_SENSOR" is mention which is very unspecific. Is there a reason for this?

**Comment by justinbuck** [comment]
HI Soeren,

This relates to the way the vocabularies are setup.
At the top level we have dissolved gas sensors
- http://vocab.nerc.ac.uk/collection/L05/current/351/
Then there are vocabs with higher granularities like L22 which give the specific model e.g.
- http://vocab.nerc.ac.uk/collection/L22/current/TOOL1248/
If you use the explore mapping option at http://vocab.nerc.ac.uk/search_nvs/ (use L05 as the search term) it will show the connections between vocabs and granularities 

A05 is a key vocab as this give the EOV term.

I would be happy to do a show and tell on this too if you are interested.

Justin

**Comment by soerenthomsen** [comment]
Thanks Justin for explaining. Appreciated!

Indeed it would be great to have a call in January to see where to place this key information via a short link in the oxygen SOP https://oceangliderscommunity.github.io/Oxygen_SOP/README.html# 

And of course the others SOPs which are out now. 

An effective cross working group exchange would be great here.
