### ISSUE TITLE
QC flags not defined in the format specification

### ISSUE THREAD

**Issue by justinbuck** [OceanGlidersCommunity/OG-format-user-manual#44]
HI,
I can't find the definition of the QC flags in the format specification. Are we just using the same flags as in EGO? If so can add to the vocabs document.
Justin

**Comment by glidermann** [comment]
We need to check definition of QC flags at IOOS, IMOS, and others. I hope they are the same! @tcarval @kerfoot?

**Comment by justinbuck** [comment]
@glidermann 
the mapping for many flag types (includes Argo et al) https://odv.awi.de/fileadmin/user_upload/odv/misc/ODV4_QualityFlagSets.pdf 
IMOS flags https://imos.org.au/fileadmin/user_upload/shared/emii/IMOS_netCDF_usermanual_v1.2.pdf 
IOOS flags https://cdn.ioos.noaa.gov/media/2020/07/QARTOD-Data-Flags-Manual_version1.2final.pdf

**Comment by glidermann** [comment]
Thanks @justinbuck ! where do we fit in? Is something yet to be discussed and agreed upon? I think it is important to have them in the specification document from the beginning (1.0) don't you?

**Comment by justinbuck** [comment]
@glidermann if possible I believe we need to align with the GOOS (with OceanGliders being a GOOS network), so aligning with OceanSITES, Argo, DBCP, etc. Each network has slight differences or additions to their flagging convention but 90% of the flags are common.

**Comment by glidermann** [comment]
I think we should be able to agree on the meaning of the QC flags independently (and much more quickly). But maybe there are philosophical differences that will come out of that discussion (hope not). Just a quick check of other GOOS networks and make sure that we align as close as possible with the ones we see as most likely to be partnered with glider data (Argo).

**Comment by justinbuck** [comment]
Discussion at NRT QC workshop, expressed a desire Argo flags (Sylvie). Gui to raise with NRT group discussion.
To be raised with NRT QC working group
Does not align 100% with Quartod which is close to IODE.
In OG 1.0 need to specify your flag convention, then we will align in a future iteration of OceanGliders format
@justinbuck to to PR for 1.0 to ensure convention is recorded until there is harmonization. Preference for  1,2,3,4 based convention. e.g. IODE, Quartod, Argo, SDN, etc
