### ISSUE TITLE
Authorship governance

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#56]
Hi,

A list of author og OG1.0 has been established based on the participant to the meetings we had in 2020 and 2021. This is giving the authors the responsibility of this version of the document.

However, the document will evolve and the list of authors too. And we need to set some governance rules to make sure these evolutions are well considered within the OceanGliders data management team. (e.g., rotation pace, mandate of the author team, number of members, rules on diversity - geographical, gender balance, carreer stage, etc...)

No suggestion yet (sorry), but the issue is raised now ;)
++
V.

**Comment by justinbuck** [comment]
@vturpin  We need to add Emma Slater and Mark Hebden to the author list

**Comment by castelao** [comment]
@justinbuck and @vturpin , I think you're talking about two different things.

The list of contributions could be defined similarly to what @soerenthomsen did for the Oxygen SOP. All contributions should be respected and valued, thus all contributors should be listed, together with what was their contributions/participation.

The list that @vturpin defined based on the participation in the meetings over the last years is for the review process in GitHub and a way to allow us to move forward. There is nothing new, the same thing we have been doing all this time, but using GitHub infrastructure.

**Comment by soerenthomsen** [comment]
I agree that all contributions should be mentioned somewhere and more details are better here than less. 
It is the only way to get some appreciation for this mostly voluntary work. 

You could build on this approach: https://oceangliderscommunity.github.io/Oxygen_SOP/sections/authors_SOP_development_process.html 

A documentation like this of the process is also needed to show i.e. when submitting to OBPS.

**Comment by glidermann** [comment]
I agree, a section of contributing authors and lead authors (reviewers) such as that in the oxygen SOP shared above is needed. I see this as part of a publication with a proper outline structure (like the oxygen case) but could be drafted at any time at the main OG data format page as a new section. But who has time to do this? We should make a priority to-do list and find help in the community with the understanding that we are volunteers.

**Comment by emmerbodc** [comment]
I think this issue can be closed now we have a list of authors and contributors in the manual
