### ISSUE TITLE
DEPLOYMENT attributes

### ISSUE THREAD

**Issue by castelao** [OceanGlidersCommunity/OG-format-user-manual#58]
@soerenthomsen raised on #35 some questions related to DEPLOYMENT. Should the example template be simplified or the OG format document expanded? Registering here so we don't lose it.

"Standard_name, calender, units and axis is missing in OG_Format.adoc"

"again all these detailed information on standard name, units, valid_max etc is not given in the "Deployment information section of OG_Format.adoc, maybe this is wanted to keep it short but a link to the other date, lon and lat section in the document might help."

**Comment by justinbuck** [comment]
@castelao  OG format document expanded is my preference in the first instance, by reducing we will likely be going against decision reached in the design process.

**Comment by vturpin** [comment]
I agree with @justinbuck. 
We should expand the format to better control this information, not very usefull for data user but critical for metadata user.

**Comment by castelao** [comment]
I'm also inclined toward an expanded version so that it was how I did the sample prototype. The downside is to give the impression of a harder entry-level (more requirements) for new users. My suggestion here is to prioritize a complete and ideal sample file, and whenever we have a chance, include in the examples a minimalist version containing only the required components. Such a minimalist version would probably be also useful for software development.

I just realized, @justinbuck your comment was about the sample CDL or the OG-Format document itself?

**Comment by glidermann** [comment]
I agree, we should expand the format described in the document with the same deployment information attributes for latitude and longitude time as the other lat/lon/time variables in the file. Is that a correct understanding of the issue @castelao and @justinbuck ?
