### ISSUE TITLE
DEPLOYMENT_DATE

### ISSUE THREAD

**Issue by castelao** [OceanGlidersCommunity/OG-format-user-manual#59]
This question was raised by @vturpin on #35.

Currently, the OG format defines DEPLOYMENT_DATE of datetime string. In that case, it should indeed follow ISO. The other alternative would be to follow the TIME and TIME_GPS using double and declare units and calendar. My suggestion is to follow TIME, and probably rename this variable to DEPLOYMENT_TIME to be coherent.

Thanks @vturpin !

**Comment by justinbuck** [comment]
@vturpin by changing the variable name do we lose backward compatibility with EGO? I have no preference on ISO versus aligning with TIME.

**Comment by vturpin** [comment]
Reprocessing the history will anyway be an issue for every DAC or GDAC. But I don't think this change is a big issue.

I see more coherence in using DEPLOYMENT_TIME than DEPLOYMENT_DATE, however: 
This information is collected by operators at sea (with lat and lon). So it should be human readable (writable I should say) 
It does not need to be very precise neither.
I would go for DEPLOYMENT_TIME (for coherence) following ISO 8601 : YYYY-MM-DDThh:mm:ss (e.g. 2019-09-26T07:58:30). In the time zone of the deployment location.

**Comment by glidermann** [comment]
Agreed: we need to update the OG_Format doc to reflect the prototype (i.e. DEPLOYMENT_TIME in iso as is done for other TIME variables in the prototype). This can be closed as soon as that is done (#58 ). Volunteers?

**Comment by vturpin** [comment]
PR #62 to update the document and #63 to update the prototype in line with this issue.
