### ISSUE TITLE
"BP - evoultion process  - reporting - agenda" sections

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#64]
These sections should be remove from the core document.
Reporting and agenda can be removed.
BP and evolution process should be edited somehowere else.

**Comment by justinbuck** [comment]
As long as we cross link the separated documents in the repository so people don't get lost I do not see an issue with this

**Comment by glidermann** [comment]
Sorry but I do not see these sections anywhere or any PR related to this proposed change. Can you please make PR on "core document" whatever that is? Then we can approve or edit to cut/paste to a new doc and replace with links.

**Comment by vturpin** [comment]
@glidermann, sorry using "core document", I was thinking of the "main document" (i.e OG_Format.adoc), here ; https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/OG_Format.adoc#evolution-process-the-inclusion-of-new-variables

Before any PR I would like to have your opinion on this question. Should the Reporting and agenda sections be in the main document ? 
Justin seems ok to remove it as long as we do not loose the information and link the main document to the other elements (i.e. evolution process and BP).
Re-reading the main doc, maybe the BP section can remain in the main document...

**Comment by glidermann** [comment]
I think a few lines summary and link (when it is formed) to the full description of BP is good. Another doc could be linked with evolution process, reporting and agenda (better "plan"). (really part of same process I guess).

**Comment by justinbuck** [comment]
Text has been udpated for 1.0
