### ISSUE TITLE
How to organize the vocab section

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#65]
So far the list of controled vocabularies are available on a google doc (linked to "OG_format.adoc"). 

I think we should move those list to the Github repo, but I don't know how to do that exactly.
First : Do you agree to have the list here ?
Second : Any idea on how to do that ?

**Comment by justinbuck** [comment]
HI @vturpin , @castelao has already transferred the document to this github repo, looking for the link now, we need to add the link to the live OG document.
Justin

**Comment by glidermann** [comment]
agreed, how and where to link in OG document? Who?

**Comment by vturpin** [comment]
Who : We could share the work load. I will be part of it for sure.
How : The idea is to request NVS to create and store OceanGliders vocab. Can we create and issue for each collection, transfer the list of vocabularies in the different issues and when we have a list agreed, submit the collection to NVS for creation and storage ?

**Comment by emmerbodc** [comment]
I think this can be closed now as we have a vocab manual
