### ISSUE TITLE
PLATFORM_CODE variable name

### ISSUE THREAD

**Issue by bodcmahe** [OceanGlidersCommunity/OG-format-user-manual#72]
I have had a conversation this week with French/Canadian glider data managers who find the EGO term 'PLATFORM_CODE' confusing. They are expecting to populate with the 4 digit ICES platform code e.g. '35ZZ' (akin to a ship_code), but this part of the EGO format is actually used to capture the informal name of the glider e.g. 'pytheas'. 

We retain 'PLATFORM_CODE' in the OG format (again, populated with the nickname of the glider). Would 'PLATFORM_NAME' be less confusing? That, together with the other identifiers (PLATFORM_SERIAL_NUMBER, WMO_IDENTIFIER, ICE_CODE) would perhaps be clearer?

Like I say, this came from a conversation earlier this week, hence not raising this earlier!

**Comment by soerenthomsen** [comment]
Thanks @bodcmahe for bringing this up and opening an issue. This is great :)

Would you mind to ask these glider data managers to possibly also join our GitHub Community? We try to get as many glider folks into the discussion here directly to get direct community feedback etc.

**Comment by bodcmahe** [comment]
@soerenthomsen No problem! That sounds like a good plan - I will extend the invite further :)

**Comment by vturpin** [comment]
#140
