### ISSUE TITLE
Title = free text 

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#76]
The global attribute "title" is currently : "OceanGliders trajectory file"
It can become a free text since global attribute "convention" must be "CF-1.8, ACDD-1.3, OG-1.0".

I would suggest to remove the fixed value for "title" and turn conventions into a mandatory global attribute.

**Comment by castelao** [comment]
I always assumed it was a free text, but I see your point. In the document, it looks like a fixed text.

I just created two new PRs (#90 and #91) proposing those changes. I'll close this issue to keep the repo cleaner, but feel free to reopen it if you wish so.

Thanks!
