### ISSUE TITLE
Keep our Google Document or move the content to here?

### ISSUE THREAD

**Issue by castelao** [OceanGlidersCommunity/OG-format-user-manual#8]
@vturpin , thanks for creating this repository.

Is the plan to keep working on the Google Doc or moving that content to some format to be discussed inside this repo? It will require some work to convert (including tables and everything else) but I think that it would be the best in the long run.

Here it goes a second question. How will we make decisions from now on? We might need to adapt moving to here and expecting more people to participate. For instance, I propose moving the content from the Google Docs to here in a different format to be decided, and the document living here would be the main document from which it would derive all other variations. How do we make this decision?

**Comment by vturpin** [comment]
@castelao 

Don't know precisely yet. I need your light and experience with github to decide.
My first feeling was to use github to raise and manage the issues with the community and keep the google doc within the team to make it evolve for yearly release. 
That would avoid to move the google doc content to github (that seems complicated to me at first sight). The counterpart is to work with two systems (git and google doc).
But if it is possible to move google doc to Git. That could become even easier.
I think we have work on a practical solution. propose to the team and they will probably follow.

**Comment by vturpin** [comment]
I just add a look at the oxygen_SOP and after a conversation with Soeren. It seems not too complicated to move the google doc to Github.
I am really in favour of this approach now ;) Don't know if we have to do it by hand or if tools exist to do it faster...

**Comment by soerenthomsen** [comment]
I would be very curious to learn about a good approach of how a steering community / lead authors could do an organised "vote" here as we will face this during the community review which is planed for the Oxygen SOP starting in early October. @castelao any suggestion? i.e. my idea was to ask for exactly the amounts of review as we have editors assigned before accepting a change?

**Comment by vturpin** [comment]
If no tools exist I'll move the text on Github.
What I have in mind now is that the main document should be published (on OBPS) with a DOI and landing page.
The evolving document should be on Github, open for "pull request" and discussion to anyone and managed by a shorter team.
