### ISSUE TITLE
add GPS QC  variables

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#82]
We should add the LATITUDE_GPS_QC, LONGITUDE_GPS_QC and TIME_GPS_QC in the format and the prototype.
Or remove the ancillary_variable from the variable attributes : LATITUDE_GPS:ancillary_variables = "LATITUDE_GPS_QC"

I am in favor of adding the LATITUDE_GPS_QC, LONGITUDE_GPS_QC and TIME_GPS_QC in the format

**Comment by castelao** [comment]
Good point @vturpin . I'm addressing that on #89. Let's move any discussion on this subject to there. Thanks!
