### ISSUE TITLE
ICES code

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#83]
the long name attribute of ICES_CODE variable is currently "ices code"
I suggest to change it into "ices code of the glider" to make it clearer that we are not talking about the ices code of the ship used to deploy the glider.
ICES code for gliders are not so used yet. Ices are known for the ships.

**Comment by bodcmahe** [comment]
Sensible suggestion Victor. Perhaps even 'ICES platform code of the glider' to avoid ambiguity completely - ICES manage various vocabularies. Just a thought...

**Comment by castelao** [comment]
@bodcmahe , thanks for your suggestion. There is an active PR already to address this. Let's converge the discussion over there so we don't risk missing anyone's opinion on this matter.

I'll close this issue to avoid divergence, and let's continue over #113.
